# Generated by Django 4.0.5 on 2022-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedias',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Medias'},
        ),
        migrations.AlterField(
            model_name='socialmedias',
            name='image',
            field=models.ImageField(upload_to='icon/'),
        ),
    ]
