# Generated by Django 4.0.5 on 2022-11-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greet',
            new_name='Greetings',
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AlterModelOptions(
            name='greetings',
            options={'verbose_name': 'Greeting', 'verbose_name_plural': 'Greetings'},
        ),
    ]
